if(NOT TESTFRAMEWORK_DISABLE_QTESTS)
  IF(USE_QT5)
    SET(QT_DEP Qt5Widgets Qt5Core)
  ELSEIF(USE_QT4)
  SET(QT_DEP QT)
  ENDIF()
endif()

# allow for tests to be disabled and no testing harness to be compiled.
IF(${PROJECT_NAME}_ENABLE_TESTS)
  TRIBITS_PACKAGE_DEFINE_DEPENDENCIES(
    LIB_REQUIRED_PACKAGES googletest
    LIB_REQUIRED_TPLS ${QT_DEP}
  )
ELSE()
  TRIBITS_PACKAGE_DEFINE_DEPENDENCIES()
ENDIF()

