IF(USE_QT5 AND TPL_ENABLE_Qt5Core)
 SET(QT_DEP Qt5Widgets Qt5Core)
ELSEIF(USE_QT4 AND TPL_ENABLE_QT)
 SET(QT_DEP QT)
ENDIF()

TRIBITS_PACKAGE_DEFINE_DEPENDENCIES(
  LIB_REQUIRED_PACKAGES googletest
  LIB_REQUIRED_TPLS ${QT_DEP}
)

